In [14]:
import numpy as np
import scipy.linalg as slin

UsageError: Line magic function `%%time` not found.


### scipy.linalg vs numpy.linalg
scipy.linalg contains all the functions in numpy.linalg. plus some other more advanced ones not contained in numpy.linalg.

Another advantage of using scipy.linalg over numpy.linalg is that it is always compiled with BLAS/LAPACK support, while for NumPy this is optional. Therefore, the SciPy version might be faster depending on how NumPy was installed.

Therefore, unless you don’t want to add scipy as a dependency to your numpy program, use scipy.linalg instead of numpy.linalg.

### Finding the inverse

In [4]:
a=np.array([[1,3,5],
           [2,3,4],[5,6,3]])
slin.inv(a)

array([[-1.25      ,  1.75      , -0.25      ],
       [ 1.16666667, -1.83333333,  0.5       ],
       [-0.25      ,  0.75      , -0.25      ]])

In [5]:
a.dot(slin.inv(a))

array([[ 1.00000000e+00, -4.44089210e-16,  0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00,  1.11022302e-16],
       [-9.99200722e-16,  8.88178420e-16,  1.00000000e+00]])

In [11]:
p=np.array([[1,2,3,4,5],
            [6,67,8, 9,45],
            [13,24,35,34,65],
            [23,432,12,32,43],
            [23,435,564,23,23]])
slin.inv(p)

array([[-2.39766424e+00, -2.11389412e-01,  3.11882862e-01,
         3.08467611e-02, -4.25878242e-03],
       [ 6.70852348e-02,  7.37754568e-03, -1.11837533e-02,
         1.27449750e-03,  2.05427881e-04],
       [ 1.39557627e-02,  1.36927788e-03, -1.32336581e-03,
        -2.02049332e-03,  1.80450747e-03],
       [ 7.11667027e-01, -1.12401127e-03, -5.40188350e-02,
         3.07387681e-04, -4.23826980e-04],
       [ 7.49916743e-02,  3.94045065e-02, -1.38939835e-02,
        -5.71276537e-03,  2.59424343e-05]])

### solving a linear system
x+3y+5z=10 <br>
2x+5y+z=8 <br>
2x+3y+8z=3

In [15]:
a=np.array([[1,3,5],
           [2,5,1],
           [2,3,8]])
b=np.array([[10],[8],[3]])
reinv=slin.inv(a)
result=reinv.dot(b)
result2=slin.solve(a,b)

In [16]:
print(result)
print(result2)


[[-9.28]
 [ 5.16]
 [ 0.76]]
[[-9.28]
 [ 5.16]
 [ 0.76]]


## Finding the determinant

In [18]:
dp=np.array([[1,2,3],[32,1,1],[5,3,2]])
res1=slin.det(dp)
print(res1)

154.00000000000003



## Norms


In [20]:
A=np.array([[1,2],[3,4]])
print(A)
slin.norm(A)
5.4772255750516612
slin.norm(A,'fro') # frobenius norm is the default
5.4772255750516612
slin.norm(A,1) # L1 norm (max column sum)
slin.norm(A,-1)
slin.norm(A,np.inf) # L inf norm (max row sum)

[[1 2]
 [3 4]]


7.0

## Least Square Methods

## Eigen values

In [27]:
eg=np.array([[1,2,3],[4,3,2],[5,4,3]])
eigenvalues,eigenvectors=slin.eig(eg)
print(eigenvalues)
print("eigenvector is",eigenvectors)

[ 8.81507291e+00+0.j -1.81507291e+00+0.j -4.31306942e-16+0.j]
eigenvector is [[ 0.4185306   0.77739002  0.40824829]
 [ 0.53923729 -0.47407921 -0.81649658]
 [ 0.73079086 -0.41341705  0.40824829]]
